# Generated by Django 4.1.1 on 2022-09-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order.')]},
        ),
    ]
